.. automodule:: pyd1.d1exceptions
   :members:
