.. automodule:: d1pythonitk.exceptions
   :members:
